name: build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      index:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
        env:
          node.name: index
          cluster.name: yente-index
          discovery.type: single-node
          xpack.security.enabled: "false"
          xpack.security.http.ssl.enabled: "false"
          xpack.security.transport.ssl.enabled: "false"
        ports:
          - 9200:9200

    env:
      YENTE_INDEX_URL: "http://index:9200/"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: setup.py
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          pip install -U pip
          sudo apt-get install -y -qq libicu-dev
          pip install -q -e ".[dev]"
          pip freeze
      - name: Run mypy strict type check
        run: |
          mypy --strict yente
      - name: Run pytest
        run: |
          pytest -v tests/unit
